name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: configure
    - name: install
      run: |
        make
        make install
    - name: test
      run: |
        sudo apt install build-essential
        sudo apt install libgtk-3-dev libwxgtk3.0-gtk3-dev
        sudo apt install libgtest-dev
        apt-get install -y wxWidgets googletest 
        cd test
        ./test.sh
