name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        sudo apt install build-essential
        sudo apt install libgtk-3-dev
        sudo apt-get install libgtest-dev
        apt-get install -y wxWidgets googletest 
        cd test
        ./test.sh
